// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDLEjJZMU-thPwqLxA1APyCBxktHlzQUoI',
//     appId: '1:681088292849:web:4cb3131c70d954a80f9650',
//     messagingSenderId: '681088292849',
//     projectId: 'pyusd-hub',
//     authDomain: 'pyusd-hub.firebaseapp.com',
//     storageBucket: 'pyusd-hub.firebasestorage.app',
//     measurementId: 'G-L8ZPBM8265',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAFU73kBjsTOHf80hjUwoLB5Chd5Ssmuuc',
//     appId: '1:681088292849:android:b06185c5b89ae7220f9650',
//     messagingSenderId: '681088292849',
//     projectId: 'pyusd-hub',
//     storageBucket: 'pyusd-hub.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBvLG_z2_fGqd_iQ2EIjvv0Ev8QXplWs6I',
//     appId: '1:681088292849:ios:3b5da6bfa061d1de0f9650',
//     messagingSenderId: '681088292849',
//     projectId: 'pyusd-hub',
//     storageBucket: 'pyusd-hub.firebasestorage.app',
//     iosBundleId: 'com.example.pyusdForensics',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBvLG_z2_fGqd_iQ2EIjvv0Ev8QXplWs6I',
//     appId: '1:681088292849:ios:3b5da6bfa061d1de0f9650',
//     messagingSenderId: '681088292849',
//     projectId: 'pyusd-hub',
//     storageBucket: 'pyusd-hub.firebasestorage.app',
//     iosBundleId: 'com.example.pyusdForensics',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDLEjJZMU-thPwqLxA1APyCBxktHlzQUoI',
//     appId: '1:681088292849:web:2c71e6ffd1c928720f9650',
//     messagingSenderId: '681088292849',
//     projectId: 'pyusd-hub',
//     authDomain: 'pyusd-hub.firebaseapp.com',
//     storageBucket: 'pyusd-hub.firebasestorage.app',
//     measurementId: 'G-F79X07G0TZ',
//   );
// }
